// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: request.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace OpenFrp.Core.Libraries.Protobuf {

  /// <summary>Holder for reflection information generated from request.proto</summary>
  public static partial class RequestReflection {

    #region Descriptor
    /// <summary>File descriptor for request.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1yZXF1ZXN0LnByb3RvIrsCCgtSZXF1ZXN0QmFzZRIcCgZhY3Rpb24YASAB",
            "KA4yDC5SZXF1ZXN0VHlwZRIoCgxsb2dpblJlcXVlc3QYAiABKAsyDS5Mb2dp",
            "blJlcXVlc3RIAIgBARIkCgpmcnBSZXF1ZXN0GAMgASgLMgsuRnJwUmVxdWVz",
            "dEgBiAEBEiUKC2xvZ3NSZXF1ZXN0GAQgASgLMgsuTG9nc1JlcWVzdEgCiAEB",
            "EhcKCmNvbmZpZ0pzb24YBSABKAlIA4gBARIsCg5ub3RpZml5UmVxdWVzdBgG",
            "IAEoCzIPLk5vdGlmbHlSZXF1ZXN0SASIAQFCDwoNX2xvZ2luUmVxdWVzdEIN",
            "CgtfZnJwUmVxdWVzdEIOCgxfbG9nc1JlcXVlc3RCDQoLX2NvbmZpZ0pzb25C",
            "EQoPX25vdGlmaXlSZXF1ZXN0ImMKDExvZ2luUmVxdWVzdBIVCg1hdXRob3Jp",
            "emF0aW9uGAEgASgJEhEKCXNlc3Npb25JZBgCIAEoCRIUCgx1c2VySW5mb0pz",
            "b24YAyABKAkSEwoLYWNjb3VudEpzb24YBCABKAkiJAoKRnJwUmVxdWVzdBIW",
            "Cg51c2VyVHVubmVsSnNvbhgBIAEoCSIYCgpMb2dzUmVxZXN0EgoKAmlkGAEg",
            "ASgFIiUKDk5vdGlmbHlSZXF1ZXN0EhMKC3R1bm5uZWxKc29uGAEgASgJKr8C",
            "CgtSZXF1ZXN0VHlwZRIaChZDTElFTlRfUFVTSF9MT0dJTlNUQVRFEAASGgoW",
            "Q0xJRU5UX1BVU0hfQ0xFQVJMT0dJThABEhUKEUNMSUVOVF9GUlBDX1NUQVJU",
            "EAISFQoRQ0xJRU5UX0ZSUENfQ0xPU0UQAxITCg9DTElFTlRfR0VUX0xPR1MQ",
            "BBIfChtDTElFTlRfR0VUX1JVTk5JTkdUVU5ORUxTSUQQBRIcChhDTElFTlRf",
            "R0VUX1JVTk5JTkdUVU5ORUwQBhIVChFDTElFTlRfQ0xFQVJfTE9HUxAHEhYK",
            "EkNMSUVOVF9QVVNIX0NPTkZJRxAIEhMKD0NMSUVOVF9DTE9TRV9JTxAJEhkK",
            "FVNFUlZFUl9VUERBVEVfVFVOTkVMUxAKEhcKE1NFUlZFUl9TRU5EX05PVElG",
            "SVkQC0IiqgIfT3BlbkZycC5Db3JlLkxpYnJhcmllcy5Qcm90b2J1ZmIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::OpenFrp.Core.Libraries.Protobuf.RequestType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenFrp.Core.Libraries.Protobuf.RequestBase), global::OpenFrp.Core.Libraries.Protobuf.RequestBase.Parser, new[]{ "Action", "LoginRequest", "FrpRequest", "LogsRequest", "ConfigJson", "NotifiyRequest" }, new[]{ "LoginRequest", "FrpRequest", "LogsRequest", "ConfigJson", "NotifiyRequest" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenFrp.Core.Libraries.Protobuf.LoginRequest), global::OpenFrp.Core.Libraries.Protobuf.LoginRequest.Parser, new[]{ "Authorization", "SessionId", "UserInfoJson", "AccountJson" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenFrp.Core.Libraries.Protobuf.FrpRequest), global::OpenFrp.Core.Libraries.Protobuf.FrpRequest.Parser, new[]{ "UserTunnelJson" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenFrp.Core.Libraries.Protobuf.LogsReqest), global::OpenFrp.Core.Libraries.Protobuf.LogsReqest.Parser, new[]{ "Id" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::OpenFrp.Core.Libraries.Protobuf.NotiflyRequest), global::OpenFrp.Core.Libraries.Protobuf.NotiflyRequest.Parser, new[]{ "TunnnelJson" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum RequestType {
    [pbr::OriginalName("CLIENT_PUSH_LOGINSTATE")] ClientPushLoginstate = 0,
    [pbr::OriginalName("CLIENT_PUSH_CLEARLOGIN")] ClientPushClearlogin = 1,
    [pbr::OriginalName("CLIENT_FRPC_START")] ClientFrpcStart = 2,
    [pbr::OriginalName("CLIENT_FRPC_CLOSE")] ClientFrpcClose = 3,
    [pbr::OriginalName("CLIENT_GET_LOGS")] ClientGetLogs = 4,
    [pbr::OriginalName("CLIENT_GET_RUNNINGTUNNELSID")] ClientGetRunningtunnelsid = 5,
    [pbr::OriginalName("CLIENT_GET_RUNNINGTUNNEL")] ClientGetRunningtunnel = 6,
    [pbr::OriginalName("CLIENT_CLEAR_LOGS")] ClientClearLogs = 7,
    [pbr::OriginalName("CLIENT_PUSH_CONFIG")] ClientPushConfig = 8,
    [pbr::OriginalName("CLIENT_CLOSE_IO")] ClientCloseIo = 9,
    [pbr::OriginalName("SERVER_UPDATE_TUNNELS")] ServerUpdateTunnels = 10,
    [pbr::OriginalName("SERVER_SEND_NOTIFIY")] ServerSendNotifiy = 11,
  }

  #endregion

  #region Messages
  public sealed partial class RequestBase : pb::IMessage<RequestBase>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RequestBase> _parser = new pb::MessageParser<RequestBase>(() => new RequestBase());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RequestBase> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenFrp.Core.Libraries.Protobuf.RequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequestBase() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequestBase(RequestBase other) : this() {
      action_ = other.action_;
      loginRequest_ = other.loginRequest_ != null ? other.loginRequest_.Clone() : null;
      frpRequest_ = other.frpRequest_ != null ? other.frpRequest_.Clone() : null;
      logsRequest_ = other.logsRequest_ != null ? other.logsRequest_.Clone() : null;
      configJson_ = other.configJson_;
      notifiyRequest_ = other.notifiyRequest_ != null ? other.notifiyRequest_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequestBase Clone() {
      return new RequestBase(this);
    }

    /// <summary>Field number for the "action" field.</summary>
    public const int ActionFieldNumber = 1;
    private global::OpenFrp.Core.Libraries.Protobuf.RequestType action_ = global::OpenFrp.Core.Libraries.Protobuf.RequestType.ClientPushLoginstate;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::OpenFrp.Core.Libraries.Protobuf.RequestType Action {
      get { return action_; }
      set {
        action_ = value;
      }
    }

    /// <summary>Field number for the "loginRequest" field.</summary>
    public const int LoginRequestFieldNumber = 2;
    private global::OpenFrp.Core.Libraries.Protobuf.LoginRequest loginRequest_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::OpenFrp.Core.Libraries.Protobuf.LoginRequest LoginRequest {
      get { return loginRequest_; }
      set {
        loginRequest_ = value;
      }
    }

    /// <summary>Field number for the "frpRequest" field.</summary>
    public const int FrpRequestFieldNumber = 3;
    private global::OpenFrp.Core.Libraries.Protobuf.FrpRequest frpRequest_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::OpenFrp.Core.Libraries.Protobuf.FrpRequest FrpRequest {
      get { return frpRequest_; }
      set {
        frpRequest_ = value;
      }
    }

    /// <summary>Field number for the "logsRequest" field.</summary>
    public const int LogsRequestFieldNumber = 4;
    private global::OpenFrp.Core.Libraries.Protobuf.LogsReqest logsRequest_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::OpenFrp.Core.Libraries.Protobuf.LogsReqest LogsRequest {
      get { return logsRequest_; }
      set {
        logsRequest_ = value;
      }
    }

    /// <summary>Field number for the "configJson" field.</summary>
    public const int ConfigJsonFieldNumber = 5;
    private string configJson_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ConfigJson {
      get { return configJson_ ?? ""; }
      set {
        configJson_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "configJson" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasConfigJson {
      get { return configJson_ != null; }
    }
    /// <summary>Clears the value of the "configJson" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearConfigJson() {
      configJson_ = null;
    }

    /// <summary>Field number for the "notifiyRequest" field.</summary>
    public const int NotifiyRequestFieldNumber = 6;
    private global::OpenFrp.Core.Libraries.Protobuf.NotiflyRequest notifiyRequest_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::OpenFrp.Core.Libraries.Protobuf.NotiflyRequest NotifiyRequest {
      get { return notifiyRequest_; }
      set {
        notifiyRequest_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RequestBase);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RequestBase other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Action != other.Action) return false;
      if (!object.Equals(LoginRequest, other.LoginRequest)) return false;
      if (!object.Equals(FrpRequest, other.FrpRequest)) return false;
      if (!object.Equals(LogsRequest, other.LogsRequest)) return false;
      if (ConfigJson != other.ConfigJson) return false;
      if (!object.Equals(NotifiyRequest, other.NotifiyRequest)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Action != global::OpenFrp.Core.Libraries.Protobuf.RequestType.ClientPushLoginstate) hash ^= Action.GetHashCode();
      if (loginRequest_ != null) hash ^= LoginRequest.GetHashCode();
      if (frpRequest_ != null) hash ^= FrpRequest.GetHashCode();
      if (logsRequest_ != null) hash ^= LogsRequest.GetHashCode();
      if (HasConfigJson) hash ^= ConfigJson.GetHashCode();
      if (notifiyRequest_ != null) hash ^= NotifiyRequest.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Action != global::OpenFrp.Core.Libraries.Protobuf.RequestType.ClientPushLoginstate) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Action);
      }
      if (loginRequest_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(LoginRequest);
      }
      if (frpRequest_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(FrpRequest);
      }
      if (logsRequest_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(LogsRequest);
      }
      if (HasConfigJson) {
        output.WriteRawTag(42);
        output.WriteString(ConfigJson);
      }
      if (notifiyRequest_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(NotifiyRequest);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Action != global::OpenFrp.Core.Libraries.Protobuf.RequestType.ClientPushLoginstate) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Action);
      }
      if (loginRequest_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(LoginRequest);
      }
      if (frpRequest_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(FrpRequest);
      }
      if (logsRequest_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(LogsRequest);
      }
      if (HasConfigJson) {
        output.WriteRawTag(42);
        output.WriteString(ConfigJson);
      }
      if (notifiyRequest_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(NotifiyRequest);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Action != global::OpenFrp.Core.Libraries.Protobuf.RequestType.ClientPushLoginstate) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Action);
      }
      if (loginRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LoginRequest);
      }
      if (frpRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FrpRequest);
      }
      if (logsRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LogsRequest);
      }
      if (HasConfigJson) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ConfigJson);
      }
      if (notifiyRequest_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NotifiyRequest);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RequestBase other) {
      if (other == null) {
        return;
      }
      if (other.Action != global::OpenFrp.Core.Libraries.Protobuf.RequestType.ClientPushLoginstate) {
        Action = other.Action;
      }
      if (other.loginRequest_ != null) {
        if (loginRequest_ == null) {
          LoginRequest = new global::OpenFrp.Core.Libraries.Protobuf.LoginRequest();
        }
        LoginRequest.MergeFrom(other.LoginRequest);
      }
      if (other.frpRequest_ != null) {
        if (frpRequest_ == null) {
          FrpRequest = new global::OpenFrp.Core.Libraries.Protobuf.FrpRequest();
        }
        FrpRequest.MergeFrom(other.FrpRequest);
      }
      if (other.logsRequest_ != null) {
        if (logsRequest_ == null) {
          LogsRequest = new global::OpenFrp.Core.Libraries.Protobuf.LogsReqest();
        }
        LogsRequest.MergeFrom(other.LogsRequest);
      }
      if (other.HasConfigJson) {
        ConfigJson = other.ConfigJson;
      }
      if (other.notifiyRequest_ != null) {
        if (notifiyRequest_ == null) {
          NotifiyRequest = new global::OpenFrp.Core.Libraries.Protobuf.NotiflyRequest();
        }
        NotifiyRequest.MergeFrom(other.NotifiyRequest);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Action = (global::OpenFrp.Core.Libraries.Protobuf.RequestType) input.ReadEnum();
            break;
          }
          case 18: {
            if (loginRequest_ == null) {
              LoginRequest = new global::OpenFrp.Core.Libraries.Protobuf.LoginRequest();
            }
            input.ReadMessage(LoginRequest);
            break;
          }
          case 26: {
            if (frpRequest_ == null) {
              FrpRequest = new global::OpenFrp.Core.Libraries.Protobuf.FrpRequest();
            }
            input.ReadMessage(FrpRequest);
            break;
          }
          case 34: {
            if (logsRequest_ == null) {
              LogsRequest = new global::OpenFrp.Core.Libraries.Protobuf.LogsReqest();
            }
            input.ReadMessage(LogsRequest);
            break;
          }
          case 42: {
            ConfigJson = input.ReadString();
            break;
          }
          case 50: {
            if (notifiyRequest_ == null) {
              NotifiyRequest = new global::OpenFrp.Core.Libraries.Protobuf.NotiflyRequest();
            }
            input.ReadMessage(NotifiyRequest);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Action = (global::OpenFrp.Core.Libraries.Protobuf.RequestType) input.ReadEnum();
            break;
          }
          case 18: {
            if (loginRequest_ == null) {
              LoginRequest = new global::OpenFrp.Core.Libraries.Protobuf.LoginRequest();
            }
            input.ReadMessage(LoginRequest);
            break;
          }
          case 26: {
            if (frpRequest_ == null) {
              FrpRequest = new global::OpenFrp.Core.Libraries.Protobuf.FrpRequest();
            }
            input.ReadMessage(FrpRequest);
            break;
          }
          case 34: {
            if (logsRequest_ == null) {
              LogsRequest = new global::OpenFrp.Core.Libraries.Protobuf.LogsReqest();
            }
            input.ReadMessage(LogsRequest);
            break;
          }
          case 42: {
            ConfigJson = input.ReadString();
            break;
          }
          case 50: {
            if (notifiyRequest_ == null) {
              NotifiyRequest = new global::OpenFrp.Core.Libraries.Protobuf.NotiflyRequest();
            }
            input.ReadMessage(NotifiyRequest);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 以下部分为二级子项
  /// </summary>
  public sealed partial class LoginRequest : pb::IMessage<LoginRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LoginRequest> _parser = new pb::MessageParser<LoginRequest>(() => new LoginRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LoginRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenFrp.Core.Libraries.Protobuf.RequestReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LoginRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LoginRequest(LoginRequest other) : this() {
      authorization_ = other.authorization_;
      sessionId_ = other.sessionId_;
      userInfoJson_ = other.userInfoJson_;
      accountJson_ = other.accountJson_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LoginRequest Clone() {
      return new LoginRequest(this);
    }

    /// <summary>Field number for the "authorization" field.</summary>
    public const int AuthorizationFieldNumber = 1;
    private string authorization_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Authorization {
      get { return authorization_; }
      set {
        authorization_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sessionId" field.</summary>
    public const int SessionIdFieldNumber = 2;
    private string sessionId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SessionId {
      get { return sessionId_; }
      set {
        sessionId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "userInfoJson" field.</summary>
    public const int UserInfoJsonFieldNumber = 3;
    private string userInfoJson_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserInfoJson {
      get { return userInfoJson_; }
      set {
        userInfoJson_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "accountJson" field.</summary>
    public const int AccountJsonFieldNumber = 4;
    private string accountJson_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AccountJson {
      get { return accountJson_; }
      set {
        accountJson_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LoginRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LoginRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Authorization != other.Authorization) return false;
      if (SessionId != other.SessionId) return false;
      if (UserInfoJson != other.UserInfoJson) return false;
      if (AccountJson != other.AccountJson) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Authorization.Length != 0) hash ^= Authorization.GetHashCode();
      if (SessionId.Length != 0) hash ^= SessionId.GetHashCode();
      if (UserInfoJson.Length != 0) hash ^= UserInfoJson.GetHashCode();
      if (AccountJson.Length != 0) hash ^= AccountJson.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Authorization.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Authorization);
      }
      if (SessionId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SessionId);
      }
      if (UserInfoJson.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(UserInfoJson);
      }
      if (AccountJson.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(AccountJson);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Authorization.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Authorization);
      }
      if (SessionId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SessionId);
      }
      if (UserInfoJson.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(UserInfoJson);
      }
      if (AccountJson.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(AccountJson);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Authorization.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Authorization);
      }
      if (SessionId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SessionId);
      }
      if (UserInfoJson.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserInfoJson);
      }
      if (AccountJson.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AccountJson);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LoginRequest other) {
      if (other == null) {
        return;
      }
      if (other.Authorization.Length != 0) {
        Authorization = other.Authorization;
      }
      if (other.SessionId.Length != 0) {
        SessionId = other.SessionId;
      }
      if (other.UserInfoJson.Length != 0) {
        UserInfoJson = other.UserInfoJson;
      }
      if (other.AccountJson.Length != 0) {
        AccountJson = other.AccountJson;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Authorization = input.ReadString();
            break;
          }
          case 18: {
            SessionId = input.ReadString();
            break;
          }
          case 26: {
            UserInfoJson = input.ReadString();
            break;
          }
          case 34: {
            AccountJson = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Authorization = input.ReadString();
            break;
          }
          case 18: {
            SessionId = input.ReadString();
            break;
          }
          case 26: {
            UserInfoJson = input.ReadString();
            break;
          }
          case 34: {
            AccountJson = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class FrpRequest : pb::IMessage<FrpRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FrpRequest> _parser = new pb::MessageParser<FrpRequest>(() => new FrpRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FrpRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenFrp.Core.Libraries.Protobuf.RequestReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrpRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrpRequest(FrpRequest other) : this() {
      userTunnelJson_ = other.userTunnelJson_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FrpRequest Clone() {
      return new FrpRequest(this);
    }

    /// <summary>Field number for the "userTunnelJson" field.</summary>
    public const int UserTunnelJsonFieldNumber = 1;
    private string userTunnelJson_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserTunnelJson {
      get { return userTunnelJson_; }
      set {
        userTunnelJson_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FrpRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FrpRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserTunnelJson != other.UserTunnelJson) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UserTunnelJson.Length != 0) hash ^= UserTunnelJson.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UserTunnelJson.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserTunnelJson);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UserTunnelJson.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserTunnelJson);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UserTunnelJson.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserTunnelJson);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FrpRequest other) {
      if (other == null) {
        return;
      }
      if (other.UserTunnelJson.Length != 0) {
        UserTunnelJson = other.UserTunnelJson;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UserTunnelJson = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            UserTunnelJson = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class LogsReqest : pb::IMessage<LogsReqest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LogsReqest> _parser = new pb::MessageParser<LogsReqest>(() => new LogsReqest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LogsReqest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenFrp.Core.Libraries.Protobuf.RequestReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogsReqest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogsReqest(LogsReqest other) : this() {
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LogsReqest Clone() {
      return new LogsReqest(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LogsReqest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LogsReqest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LogsReqest other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class NotiflyRequest : pb::IMessage<NotiflyRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NotiflyRequest> _parser = new pb::MessageParser<NotiflyRequest>(() => new NotiflyRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NotiflyRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::OpenFrp.Core.Libraries.Protobuf.RequestReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NotiflyRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NotiflyRequest(NotiflyRequest other) : this() {
      tunnnelJson_ = other.tunnnelJson_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NotiflyRequest Clone() {
      return new NotiflyRequest(this);
    }

    /// <summary>Field number for the "tunnnelJson" field.</summary>
    public const int TunnnelJsonFieldNumber = 1;
    private string tunnnelJson_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TunnnelJson {
      get { return tunnnelJson_; }
      set {
        tunnnelJson_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NotiflyRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NotiflyRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TunnnelJson != other.TunnnelJson) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TunnnelJson.Length != 0) hash ^= TunnnelJson.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TunnnelJson.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TunnnelJson);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TunnnelJson.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TunnnelJson);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TunnnelJson.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TunnnelJson);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NotiflyRequest other) {
      if (other == null) {
        return;
      }
      if (other.TunnnelJson.Length != 0) {
        TunnnelJson = other.TunnnelJson;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            TunnnelJson = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            TunnnelJson = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
